### PR TITLE
Resolving issue #19 : Added Pneumonia Detection Notebook

### PR DESCRIPTION
**Pull request by AM1CODES**
I have created the notebook for detecting Pneumonia in a patient using the chest x-ray.
Additions i made:
* Added PneumoniaDetection.ipynb to Notebooks Folder

Results from model evaluation:
* Loss = 0.1803
* Accuracy = 0.9436

I have not added the data set to the datasets folder as it was too big to be included but if needed i will figure something out and make the changes.

I have not added the '.h5' file in Models folder as it was big too. I can upload it in a drive folder and update the data sets folder with a readme with the link, and i can do the same for the data set as well.

### CODE REVIEW

**Comment by utkarsh0702** [comment]
Looks great from my end. @shubhigupta991 @heflinstephenraj 
@AM1CODES Please upload the model to Google Drive and share the link.

**Review by utkarsh0702 — APPROVED** [review]
Looks great from my end. @shubhigupta991 @heflinstephenraj
@AM1CODES Please upload the model to Google Drive and share the link.

**Comment by AM1CODES** [comment]
@utkarsh0702 yes sure. I will upload the model and share the  link here itself. Is that okay?

**Review by shubhigupta991 — APPROVED** [review]

**Comment by utkarsh0702** [comment]
@AM1CODES Please provide the link to the model.

**Comment by AM1CODES** [comment]
@utkarsh0702 Here you go - [https://drive.google.com/drive/folders/1ZHVclfc6bLmbgbu__CgXMhd9KVrWBkMM?usp=sharing](url)

**Pull request merged**
