### PR TITLE
[Gssoc'21] Fix the Internal Server Error and Navbar toggle which was not working.

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue

Previously When I clicked on Predict without entering any data it leads to internal server error.
I occurs in three pages (Diabetes Prediction, Heart Disease Prediction, Cancer Prediction).
and navbar toggle was not working and website is not responsive.
I am attaching a video for better understanding of my issues.

https://user-images.githubusercontent.com/55352601/112711918-0316fc80-8ef2-11eb-8268-223bdf257c17.mp4

Closes: #119 

#### Describe the changes you've made
I am attaching a video after my changes.

https://user-images.githubusercontent.com/55352601/112713785-d9af9e00-8efc-11eb-869f-ab2fa3e2ab82.mp4

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by arpit456jain** [comment]
sir can you please add the label of level of your choice.

**Comment by arpit456jain** [comment]
@manan-bedi2908 sir please review this PR.

**Review by manan-bedi2908 — APPROVED** [review]
Very nice work!
Approved

**Comment by arpit456jain** [comment]
> Very nice work!
> Approved

Thank you so much sir...

**Pull request merged**
