### PR TITLE
Flask route for Liver Disease

### PR DESCRIPTION
**Pull request by JanhaviSoni**
## Related Issuse

Flask route for Liver Disease

Closes: #151 

Added flask route for Liver Disease . Made changes to app.py file for adding the function for liver disease prediction which renders liver.html for taking inputs and liver_result for showing the predicted result for the inputs . Also added the liver card in index.html

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer Please review PR

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer @manan-bedi2908 any changes in the PR

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer @utkarsh0702 My branch is now showing conflict . Earlier there was no conflict . How should it be resolved?

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer when will it get merged. Its been many days as of now

**Review by kritikaparmar-programmer — APPROVED** [review]
LGTM 🚀

**Pull request merged**
