### PR TITLE
Chronic Kidney Disease and Tumor Analysis

### LINKED ISSUE #12: Add a new project: Kidney disease prediction
I would like to add a new project for predicting kidney diseases. 
Using the dataset : https://www.kaggle.com/mansoordaku/ckdisease  
I am a participant of GSSOC'21

### PR DESCRIPTION
**Pull request by sudipg4112001**
Fixes #12 
Added the notebook and dataset in the required place.

### CODE REVIEW

**Comment by sudipg4112001** [comment]
Please review this PR

**Comment by kritikaparmar-programmer** [comment]
Hey @sudipg4112001 contribution period for GSSOC'21 will start from 8, I'll give my reviews tomorrow.

**Comment by sudipg4112001** [comment]
### Related issue
Fixes #18 
I have added notebook, dataset and model for tumor analysis

**Comment by sudipg4112001** [comment]
This whole PR fixes two issues #12 and #18 
### Related issues 
Fixes #12 and #18 
### Additional info
I have made all the changes from main branch and couldn't make make a separate branch due to some issues. But, all the commits done are genuine. Please, consider..!!

**Review by shubhigupta991 — CHANGES_REQUESTED** [review]
Create different PR for different issues this will help you fetch more points.

**Comment by sudipg4112001** [comment]
> Create different PR for different issues this will help you fetch more points.

Actually I have made both from the main. Now, I am facing problem in making different PRs for different issues. Please consider this PR with both the resolved issues

**Comment by kritikaparmar-programmer** [comment]
Hey @sudipg4112001 please make a different branch on your local, then push the changes, never ever push changes on the main branch, take your time and submit a new pr. Also, make different PR's for different issues.
If you need any kind of help then dm me on discord's Gssoc.

**Comment by sudipg4112001** [comment]
Okay.. I need time for making the changes..

**Comment by kritikaparmar-programmer** [comment]
@sudipg4112001 take your time. Just make sure to make different pr's this will get you more points and also this time first make a different branch. Happy Coding :)

**Pull request closed without merging**
