### PR TITLE
[Gssoc'21] Added the 404 page and the code to handle 404 error

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

There was no 404 page.

Closes: #172 

#### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/114273039-326f5280-9a36-11eb-9e72-44312fc7ee4e.mp4

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer kindly review my PR.

1 .I had added the code to handle 404 error

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer kindly review my PR. you had already approved 404 page in issue section . 
and please add suitable labels to it

**Comment by arpit456jain** [comment]
@utkarsh0702 can you please review my pr @kritikaparmar-programmer already approved this changes in issue section you can check it

**Review by kritikaparmar-programmer — APPROVED** [review]
Great work 🚀

**Comment by arpit456jain** [comment]
> Great work 🚀

@kritikaparmar-programmer please add labels of GSSoC21 and level 😅😅

**Pull request merged**
