### PR TITLE
[Gssoc'21] added social media icons in Footer

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

I had added some cool social media icons in footer which are fully responsive

Closes: #185 

#### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/115105890-4f98a980-9f7f-11eb-87c9-873ce725252c.mp4

## Checklist:

- [xx My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@utkarsh0702 @shubhigupta991 @kritikaparmar-programmer kindly review my PR.
and don't worry if any of social media is extra i will remove it

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer @manan-bedi2908 kindly review my PR

**Review by kritikaparmar-programmer — CHANGES_REQUESTED** [review]
@arpit456jain We don't need all these icons. Just add a github icon with the link to this repo.

**Comment by arpit456jain** [comment]
> @arpit456jain We don't need all these icons. Just add a github icon with the link to this repo.

done @kritikaparmar-programmer

**Comment by arpit456jain** [comment]
final

**Review by manan-bedi2908 — APPROVED** [review]
Looks fine!

**Review by kritikaparmar-programmer — APPROVED** [review]

**Pull request merged**
