### PR TITLE
Added Disease Page for user and parkinsons disease detect page #154 #155

### PR DESCRIPTION
**Pull request by Borahb**
## Related Issue

- Page for Parkinsons' disease detect  was to be made.

Closes:  #155 

#### Describe the changes you've made

Made page for parkinsons disease detect.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by utkarsh0702** [comment]
@Borahb  Please update the fork, or again fork it to remove unnecessary files. And create 2 separate prs for 2 different issues as it will help us allocate you correct points.

**Comment by Borahb** [comment]
@utkarsh0702 Updated this PR for Parkinson's disease Page.

**Comment by utkarsh0702** [comment]
@Borahb Please fork the repo again and then add your files for Parkinson's page.

**Comment by utkarsh0702** [comment]
@Borahb Please provide update?

**Comment by Borahb** [comment]
@utkarsh0702  I have updated through upstream. I pulled upstream main to the branch.

**Comment by Borahb** [comment]
@utkarsh0702 And it does not make any change to the repo, after I forked it again.

**Comment by utkarsh0702** [comment]
close #155

**Pull request merged**
