### PR TITLE
Stroke Prediction with Flask route

### PR DESCRIPTION
**Pull request by barnamensch056**
## Related Issue

- In the website a route for stroke prediction is added.

Closes: #164 

#### Describe the changes you've made

In a different branch 'stroke', app.py a function is made to predict the stroke that is stored in pickle file and returns the render the HTML template stroke.html and with giving inputs as suggested it will give the result of prediction.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by barnamensch056** [comment]
Hey mentors @utkarsh0702 @shubhigupta991 kindly review my PR.

**Review by kritikaparmar-programmer — APPROVED** [review]
Great work @barnamensch056 🚀

**Comment by barnamensch056** [comment]
> Great work @barnamensch056 🚀

Thank you Kritika :-)

**Review by shubhigupta991 — APPROVED** [review]
This was your first request. Therefore I am approving the changes from my end but please try to contribute into the dev branch from the next time. Good work💕

**Review by manan-bedi2908 — APPROVED** [review]
Good work!!

**Comment by barnamensch056** [comment]
> This was your first request. Therefore I am approving the changes from my end but please try to contribute into the dev branch from the next time. Good work💕

Yeah sure I'll make changes in the dev brunch from the next time.

**Comment by barnamensch056** [comment]
> Good work!!

Thanks @manan-bedi2908 😊

**Pull request merged**
