### PR TITLE
Improving the efficiency of the cancer model

### PR DESCRIPTION
**Pull request by Divyang0601**
Applied Hyperparameter Tuning using GridSearchCV to improve the efficiency of the cancer model to 97% accuracy

## Related Issuse

Issue: #104 Resolved

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by shubhigupta991** [comment]
please mention the issue it resolves.

**Comment by Divyang0601** [comment]
Issue #104: Improving the efficiency/performance of the Cancer model.

**Review by shubhigupta991 — CHANGES_REQUESTED** [review]
LGTM💕. Just change the name of your .pkl so that it do not replace the pre-existing model. also i think you didnt add the model to models folder make sure you add that.

**Comment by Divyang0601** [comment]
Just made the changes requested. Kindly review

**Review by shubhigupta991 — APPROVED** [review]

**Pull request merged**
