### PR TITLE
Data visualization

### PR DESCRIPTION
**Pull request by Dishita2602**
I have solved issue **#50**
Data Visualization of cancer, fetal_health, diabetes, india_liver_patient & heart #50
Pearson Coefficient and selected features
Pair Plot
Box Plot
Count Plot
Correlation Plot
Description (Mean, Count, Std etc)

### CODE REVIEW

**Review by shubhigupta991 — CHANGES_REQUESTED** [review]
Why there are two notebooks. Create a single notebook. Also in some plots titles are not visible increase the size of plot and hence axis titles and other text

**Comment by shubhigupta991** [comment]
Any updates?

**Review by shubhigupta991 — APPROVED** [review]
LGTM💕. Just delete that copy notebook by reforking and recloning also push your code to dev branch.

**Comment by Dishita2602** [comment]
> LGTM💕. Just delete that copy notebook by reforking and recloning also push your code to dev branch.

Thank you so much ! I will delete extra file

**Comment by kritikaparmar-programmer** [comment]
Updates @Dishita2602?

**Comment by Dishita2602** [comment]
> Updates @Dishita2602?

Doing today itself

**Pull request closed without merging**
