### PR TITLE
Tumor Analysis added

### LINKED ISSUE #18: Tumor analysis
I would like to add a project based on tumor analysis for a person. Using a dataset that would contain images of brains, then I would detect whether the person is having tumor or not.

### PR DESCRIPTION
**Pull request by sudipg4112001**
### Related issue
Fixes #18 

Added notebook, model and dataset

### CODE REVIEW

**Comment by sudipg4112001** [comment]
Please review this PR

**Review by manan-bedi2908 — APPROVED** [review]
Seems fine to me!!
Nice work

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@sudipg4112001 The work you did is great 👍. A few points:
1) Try tuning the final model a bit, the accuracy is still low(try atleast for 80%)
2) Please provide the model.

**Comment by utkarsh0702** [comment]
@sudipg4112001 Please provide an update regarding the pr.

**Comment by sudipg4112001** [comment]
I am not able to get that much of accuracy.

**Comment by kritikaparmar-programmer** [comment]
Hey, @sudipg4112001 no problem if you're not able to get that much of the accuracy. 
Just provide us with the model and I'll merge the pr.

**Comment by sudipg4112001** [comment]
> Hey, @sudipg4112001 no problem if you're not able to get that much of the accuracy.
> Just provide us with the model and I'll merge the pr.

Model is already provided, with the file name 'Tumor Analysis.csv'

**Comment by utkarsh0702** [comment]
> Model is already provided, with the file name 'Tumor Analysis.csv'

@sudipg4112001 Model is not provided, the file just contains the labels. Please provide the model in .pkl format.

**Comment by kritikaparmar-programmer** [comment]
@utkarsh0702 I'm merging the pr, please add a new issue regarding the model.

**Pull request merged**
