### PR TITLE
making some changes in the documentation styling

### PR DESCRIPTION
**Pull request by kulendu**
Improving the Documentation, like highlighting the main diseases that the website can detect ->  #121

### CODE REVIEW

**Comment by shubhigupta991** [comment]
Was the issue assigned to you?

**Comment by kulendu** [comment]
I made a issue, thinking the Documentation could be improved

**Comment by shubhigupta991** [comment]
> I made a issue, thinking the Documentation could be improved

but before creating a PR you should have wait for us to assign you the issue, thats the part of code of conduct for any open source project.

**Comment by kulendu** [comment]
> > I made a issue, thinking the Documentation could be improved
> 
> but before creating a PR you should have wait for us to assign you the issue, thats the part of code of conduct for any open source project.

Ya sure. Thanks for letting me know

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@kulendu This is not some kind of documentation improvement. You just bolded few words.
Please do some significant one.

**Comment by kulendu** [comment]
Thanks @utkarsh0702 I will surely try to make some significant changes

**Pull request closed without merging**
