### PR TITLE
Pull request generated for eda-heart

### PR DESCRIPTION
**Pull request by mansi75**
## Related Issuse

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by shubhigupta991** [comment]
Which issue it resolves?

**Comment by mansi75** [comment]
@shubhigupta991 It is exploratory data analysis notebook for Heart disease data.

**Comment by shubhigupta991** [comment]
@mansi75 Have you raised any issue that has been assigned to which is resolved by this PR

**Review by shubhigupta991 — APPROVED** [review]
LGTM 💕

**Comment by shubhigupta991** [comment]
Push your changes to the dev branch. Else is fine.

**Comment by mansi75** [comment]
@shubhigupta991 Ma'am, kindly check
https://github.com/kritikaparmar-programmer/HealthCheck/pull/140

**Pull request closed without merging**
