### PR TITLE
Added disease selection page for user category

### PR DESCRIPTION
**Pull request by Borahb**
## Related Issue

-To make the disease selection page for user category

Closes: #154 

#### Describe the changes you've made

Made the disease selection page for user category.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by utkarsh0702** [comment]
@Borahb Please fork the repo again and then add your files for the category page.

**Comment by Borahb** [comment]
@utkarsh0702  Can you mention what extra files are you talking about?

**Comment by utkarsh0702** [comment]
@Borahb The extra committed files other than yours that you can see above.

**Comment by Borahb** [comment]
@utkarsh0702  I have updated the files by setting the upstream. I pulled upstream main into the branch. It should update the files.

**Comment by utkarsh0702** [comment]
@Borahb Please provide update?

**Comment by Borahb** [comment]
@utkarsh0702  I have updated through upstream.

**Comment by Borahb** [comment]
@utkarsh0702  And it does not make any change to the repo, after I forked it again.

**Review by utkarsh0702 — APPROVED** [review]

**Pull request merged**
