### PR TITLE
Diabetes Prediction

### PR DESCRIPTION
**Pull request by Manasi2001**
## Related Issue

Closes: #212 

#### Describe the changes you've made

I have worked on getting rid of outliners in detail with proper visualizations. Have also used variance inflation factor to filter out unnecessary attributes.

## Checklist:

- ✅ My code follows the style guidelines of this project.
- ✅ I have performed a self-review of my own code.
- ✅  I have commented my code, particularly in hard-to-understand areas.
- ✅ I have made corresponding changes to the documentation.
- ✅ My changes generate no new warnings.

### CODE REVIEW

**Comment by Manasi2001** [comment]
@utkarsh0702 please check out this PR and provide labels.
Thanks in advance!

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@Manasi2001 Error is not very less. Remove that statement and if your model have improved the accuracy, then attach your model also.

**Comment by Manasi2001** [comment]
@utkarsh0702 please check the updated files.

**Review by utkarsh0702 — APPROVED** [review]
@Manasi2001 LGTM.

**Comment by Manasi2001** [comment]
@utkarsh0702 please provide the labels :)

**Pull request merged**
