### PR TITLE
Adding Time series forecasting covid 19 case notebook #115 

### PR DESCRIPTION
**Pull request by ayush-raj8**
## Related Issuse
Addition of notebook that uses covid 19 cases data of over one year for a country , here India, to graphically forecast the number of fresh active and death cases daily for next 21 days.
- Info about Issue or bug

Closes: #115 

#### Describe the changes you've made

I've added a new notebook dealing with time series forecasting of covid 19 for next 3 weeks using the covid 19 data till now . Arima model has been used .
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new errors.

## Screenshots

image

### CODE REVIEW

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@ayush-raj8 The notebook looks good. Few changes are requested:
1) Please add a few visualizations.
2) If you are doing COVID19 forecasting, then you need to forecast no. of cases, no. of recovery and no, of deaths all three and provide forecasted visualization for all three.
3) Please increase the forecasted data, as it's hard to understand a lot from small test data.

**Comment by kritikaparmar-programmer** [comment]
@ayush-raj8 Please add the dataset used by you for the notebook in the Datasets folder.

**Comment by ayush-raj8** [comment]
> @ayush-raj8 Please add the dataset used by you for the notebook in the Datasets folder.

Actually the data taken into consideration is updates daily , so I've included it's source url within the program. This will always give live data whenever it is run in future

**Comment by ayush-raj8** [comment]
@utkarsh0702 I've added a new notebook in accordance with the changes , do I need to delete my forked repo and then add the new notebook ?

**Review by utkarsh0702 — APPROVED** [review]
@ayush-raj8 The notebook is looks good to me 👍
Nice work 😃

**Pull request merged**
