### PR TITLE
update in flask app

### PR DESCRIPTION
**Pull request by sujoy-coder**
## Related Issuse

- Created a new Route in flask app for Fetal Health Classification

Closes: #60 

#### Describe the changes you've made

modified in `app.py` and `index.html` and added images in `static` folder etc. Also added a new html file in `templates` folder named `fetal_health.html` etc.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | **updated screenshot** |

#### Original screenshot
Screenshot (39)

#### Updated screenshot

Screenshot (46)

Screenshot (58)

### CODE REVIEW

**Comment by manan-bedi2908** [comment]
@sujoy-coder Front end is fine , but I am not able to see the output if a person is suffering from fetal health or not. It keeps on loading for a long time

**Comment by sujoy-coder** [comment]
Hey @manan-bedi2908 ,  are you able to see the output ?
Yes it is loading very slow for 1st time... I think there is a problem with saved `fetal-health-model.pkl` 🤔

**Comment by manan-bedi2908** [comment]
@sujoy-coder I am not able to see the output

**Comment by sujoy-coder** [comment]
But In my machine I am able see the output ...

**Comment by sujoy-coder** [comment]
What should I do then?

**Comment by manan-bedi2908** [comment]
> But In my machine I am able see the output ...

Can you just show a screenshot of that?
Rest everything is fine

**Comment by sujoy-coder** [comment]
OK... I am shearing a video for the prediction... 
Please give me some time

**Comment by manan-bedi2908** [comment]
> OK... I am shearing a video for the prediction...
> Please give me some time

Sure

**Comment by manan-bedi2908** [comment]
image
I guess there is some issue in loading the bootstrap and jquery bundle

**Comment by sujoy-coder** [comment]
Here is the video Link :
https://drive.google.com/file/d/1H_I-8GUxJU4o538XzvuXWT5fr9hFVnXN/view?usp=sharing

Please Check it

**Comment by sujoy-coder** [comment]
> image
> I guess there is some issue in loading the bootstrap and jquery bundle

@manan-bedi2908  I think , the bootstrap and jquery files are imported in `layout.html`. So who created this `layout.html` file he/she import bootstrap and jquery files from `./static/vendor/` directory .

This issue can be resolve by two ways 
- by using CDN link for bootstrap and jquery
- by modifying `layout.html` file

**Comment by manan-bedi2908** [comment]
Now, I am able to see output on my machine as well

**Review by manan-bedi2908 — APPROVED** [review]
Very nice work!!

**Comment by sujoy-coder** [comment]
Hey @manan-bedi2908, Please put a `gssoc21` and `label` Label in my PR  👀

**Comment by sujoy-coder** [comment]
> Very nice work!!

🙏

**Pull request merged**
