### PR TITLE
Updated DiabetesNotebook.ipynb

### PR DESCRIPTION
**Pull request by aayushibansal2001**
#16
- Trained the model on Simple Linear Regression algorithm
- Predicted the Test set results
- Displayed the difference between actual and predicted values.

### CODE REVIEW

**Comment by aayushibansal2001** [comment]
The Update README.md commit was for issue number #9, but don't know how it got committed to this issue. How can I resolve this?

**Comment by kritikaparmar-programmer** [comment]
Hey @aayushibansal2001 there are conflicts in this branch resolve them.

**Comment by kritikaparmar-programmer** [comment]
Hey, @aayushibansal2001 you have to make different branches for different issues and never do changes in the main branch.I cannot merge this PR as in this the changes were done in the main branch of your local repo. Kindly make a different PR for both the issues, take your time, and if you want any kind of help contact the mentors or me. Happy Coding

**Comment by aayushibansal2001** [comment]
Sure! Will do that. Thanks for pointing out the mistake.

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
Add a few points to the jupyter notebook:
1) Add a few visualizations of the pandas DataFrame.
2) Provide some evaluation metrics of the model.
3) Please provide the model in the pr.

**Pull request closed without merging**
