### PR TITLE
Added Pancreatic Cancer Prediction Notebook

### PR DESCRIPTION
**Pull request by ritikkumar55**
## Related Issuse

- Info about Issue or bug

Closes: #40 

#### Describe the changes you've made

This machine learning models uses the different  algorithms  to predict whether a person suffer from 3 (pancreatic cancer) versus 2 (non-cancerous pancreas condition) and 1 (healthy). Uuse exploratory data anlaysis, data cleaning, feature selection in this notebook.
The classification models which we will use and will do some Hyperparameters optimizations are:

Logistic Regression
Decision Tree Classifier
XGBClassifier
CatBoostClassifier
LGBMClassifier

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original**
Screenshot (130)
l screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@ritikkumar55 The visualuzations are great 👍.  Please do the follow:
1) Try improving the accuracy of the model by tuning them, donot use there default values, or try using bagging or boosting algorithms.
2) Create the model using the algorithm that gives highest accuracy.
2) Please provide us model in .pkl file format.

**Comment by ritikkumar55** [comment]
> @ritikkumar55 The visualuzations are great 👍. Please do the follow:
> 
> 1. Try improving the accuracy of the model by tuning them, donot use there default values, or try using bagging or boosting algorithms.
> 2. Create the model using the algorithm that gives highest accuracy.
> 3. Please provide us model in .pkl file format.

Sure Sir @utkarsh0702

**Comment by kritikaparmar-programmer** [comment]
@ritikkumar55 updates?

**Comment by ritikkumar55** [comment]
> @ritikkumar55 updates?

@kritikaparmar-programmer Tomorrow I will submit it.

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@ritikkumar55 The pancreatic cancer notebook looks good 👍. 
1) Please run the last cells of your notebook and provide us the model.
2) don't change other people's notebooks

**Comment by kritikaparmar-programmer** [comment]
@utkarsh0702 I think he has made the changes, kindly review the changes.

**Review by utkarsh0702 — APPROVED** [review]
@ritikkumar55 Looks good to me 👍.

**Pull request merged**
