### PR TITLE
[Gssoc'21] Added the Dark mode and toggle button.

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse
I had added the dark-mode in website and the toggle for toggling it. 

Closes: #131 

#### Describe the changes you've made

I am uploading a video for better understanding my changes.

https://user-images.githubusercontent.com/55352601/113017290-ef42f300-919c-11eb-8e49-6f4c7a5ff47b.mp4

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by arpit456jain** [comment]
In previous video if you see there was some issue with position of toggle button in mobile view and navbar toggle color.
Which I fixed now.
Here is the video.

https://user-images.githubusercontent.com/55352601/113018584-53b28200-919e-11eb-8ade-14674216b2d1.mp4

**Comment by utkarsh0702** [comment]
@manan-bedi2908 Please review this pr.

**Comment by arpit456jain** [comment]
previously position of toggle button was absolute that's why it goes up on scrolling up but now it is fixed .

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer any changes to be done ?? if not kindly merge it. if possible and please add label of level of my work

**Review by kritikaparmar-programmer — APPROVED** [review]
LGTM 👍

**Comment by arpit456jain** [comment]
> LGTM 👍

Thanks for merging
LGTM means😅?

**Pull request merged**
