### PR TITLE
Improving the Diabetes model (Resolved Issue #157 )

### PR DESCRIPTION
**Pull request by Divyang0601**
## Related Issuse

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Divyang0601** [comment]
Resolved issue #157

**Review by utkarsh0702 — APPROVED** [review]
@Divyang0601 The notebook and model looks good to me. 👍

**Comment by Divyang0601** [comment]
Sorry I re-request for review by mistake

**Review by utkarsh0702 — APPROVED** [review]

**Review by shubhigupta991 — CHANGES_REQUESTED** [review]
Good work 💕 but can you close this PR and push your code into the developer branch.

**Comment by Divyang0601** [comment]
> Good work 💕 but can you close this PR and push your code into the developer branch.

Just did it. Please check out

**Pull request closed without merging**
