### PR TITLE
added welcome bot

### PR DESCRIPTION
**Pull request by Sloth-Panda**
issue no: #24

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@kritikaparmar-programmer

**Review by kritikaparmar-programmer — APPROVED** [review]
Looks Good to me. Great work 🚀

**Comment by Sloth-Panda** [comment]
@kritikaparmar-programmer @manan-bedi2908  please review this pr and also please add gssoc21 and level tags to both issue and pr

**Comment by shubhigupta991** [comment]
fixes #24

**Pull request merged**
