### PR TITLE
Parkinson

### PR DESCRIPTION
**Pull request by JanhaviSoni**
## Related Issuse

- Parkinson Disease Prediction

Closes: #32 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by utkarsh0702 — APPROVED** [review]
@JanhaviSoni The notebook  and dataset looks good from my end. 
A few points:
1) Changing the version of python won't  make a difference.
2) Please make an extra commit by adding the parkinson model to the Models directory in the repository.

**Comment by JanhaviSoni** [comment]
Please review the PR.

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
WhatsApp Image 2021-03-14 at 22 07 28

Please use a file format while creating a model and upload the model again.
Eg:
while open("parkinson_model.pkl","wb") as f:
&nbsp;&nbsp;&nbsp;&nbsp;pickle.dump(classifier,f)

I will merge the pr just after you submit the requested changes.

**Comment by JanhaviSoni** [comment]
@utkarsh0702 was this the required change or any more changes?

**Comment by utkarsh0702** [comment]
@JanhaviSoni Replace "Models/parkinson_model" file with "Models/parkinson_model.pkl" file

**Review by utkarsh0702 — APPROVED** [review]
@JanhaviSoni Perfect.

**Pull request merged**
