### PR TITLE
Added Oral Cancer Prediction Model

### PR DESCRIPTION
**Pull request by anas-ismail273**
Closes: #[48]

The following Machine Learning Models uses different algorithms to predict whether a person has an oral cancer or not.

The algorithms implemented are:
      - Decision Tree
      - RandomForest
      - Support Vector Machines

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshot
Sample of the Code

### CODE REVIEW

**Review by shubhigupta991 — APPROVED** [review]
LGTM💕. Can you push the code to dev branch instead of main branch else is fine.

**Comment by Anas-Issa** [comment]
@shubhigupta991 Sure. So I will have to close this PR and create another PR with the file pushed in the dev branch, right?

**Comment by shubhigupta991** [comment]
> @shubhigupta991 Sure. So I will have to close this PR and create another PR with the file pushed in the dev branch, right?

Yeah right? Can you do that?

**Comment by Anas-Issa** [comment]
@shubhigupta991 Yes sure I will do it

**Pull request closed without merging**
