### PR TITLE
PR for diabetic retinopathy severity detection

### PR DESCRIPTION
**Pull request by nandinib1999**
## Related Issue

Closes: #14 

#### Describe the changes you've made

I have added a .ipynb notebook for baseline modelling of diabetic retinopathy detection. It uses the dataset from Kaggle which is huge (around 9.5 GB in zipped format) and the model saved was huge as well. Hence, I have not added those to the repository.

## Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.

### CODE REVIEW

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@nandinib1999 The notebook looks good. Please attach the model.

**Review by shubhigupta991 — CHANGES_REQUESTED** [review]
Add some more evaluation methods like confusion matrix, classification report etc. 
Also do save the model in pkl format and add that file here.

**Comment by nandinib1999** [comment]
> @nandinib1999 The notebook looks good. Please attach the model.

Sure!

**Comment by nandinib1999** [comment]
> Add some more evaluation methods like confusion matrix, classification report etc.
> Also do save the model in pkl format and add that file here.

Okay sure!

**Comment by nandinib1999** [comment]
I am unable to save the model in pkl format and in .pb format is too large too upload

**Comment by utkarsh0702** [comment]
@nandinib1999 Save the model in .h5, upload it to google drive and share it using the link.

**Comment by shubhigupta991** [comment]
whats the update @nandinib1999 ?

**Comment by nandinib1999** [comment]
I shall update the MR by tomorrow. Sorry for the delay. college is really hectic with end terms approaching

**Comment by shubhigupta991** [comment]
> I shall update the MR by tomorrow. Sorry for the delay. college is really hectic with end terms approaching

okay

**Comment by nandinib1999** [comment]
https://drive.google.com/file/d/1I21obcCoqZ47bIMvQt-vK9uUPv5F6NbK/view?usp=sharing

**Comment by kritikaparmar-programmer** [comment]
@nandinib1999 Can you please upload the model to the models folder?

**Comment by nandinib1999** [comment]
> @nandinib1999 Can you please upload the model to the models folder?

The model is too big! It can't be uploaded on the GitHub repository. Even the zipped version is too large in size. That's why I have added the drive link.

**Comment by shubhigupta991** [comment]
> The model is too big! It can't be uploaded on the GitHub repository. Even the zipped version is too large in size. That's why I have added the drive link.

Did you try uploading it through command line?

**Comment by nandinib1999** [comment]
> > The model is too big! It can't be uploaded on the GitHub repository. Even the zipped version is too large in size. That's why I have added the drive link.
> 
> Did you try uploading it through command line?

Yes, I have tried. :)

**Comment by nandinib1999** [comment]
405 MB file

**Comment by kritikaparmar-programmer** [comment]
Ok, no problem @nandinib1999. Just add the link to the model in the jupyter notebook so that one can use the model from there for now.

**Comment by nandinib1999** [comment]
> Ok, no problem @nandinib1999. Just add the link to the model in the jupyter notebook so that one can use the model from there for now.
I have added it.

**Review by kritikaparmar-programmer — APPROVED** [review]

**Pull request merged**
