### PR TITLE
Fixed DiabetesNotebook.ipynb

### PR DESCRIPTION
**Pull request by aayushibansal2001**
Fixed Issue: #16

- [X] Trained the model on Simple Linear Regression algorithm
- [X] Predicted the Test set results
- [X] Displayed the difference between actual and predicted values
- [X] Added a few visualizations of the pandas DataFrame
- [X] Provided evaluation metrics of the model

### CODE REVIEW

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@aayushibansal2001 The visualizations  are great but the code for the model needs some improvement.
Few tips:
1) please don't use linear regression until it gives higher accuracy, use decisions tree, random forest, XGBRegressor or LGBRegressor.
2) Please use accuracy as one of the evaluation metrics. Other metrics can be of your choice.

**Comment by shubhigupta991** [comment]
Any updates?

**Comment by aayushibansal2001** [comment]
> Any updates?

Since I was new to Machine Learning, I was going through decision tree and random forest models. And have started implementing it. Kindly give me one more week for the desired changes.

**Comment by kritikaparmar-programmer** [comment]
Hey, @aayushibansal2001 if you're facing any kind of problem please contact the mentors or me, we are here to help you.

**Comment by utkarsh0702** [comment]
> Since I was new to Machine Learning, I was going through decision tree and random forest models. And have started implementing it. Kindly give me one more week for the desired changes.
@aayushibansal2001 Please update the PR.

**Comment by aayushibansal2001** [comment]
Hi! I have done the requested changes. Please check them.

**Comment by kritikaparmar-programmer** [comment]
@utkarsh0702 Review the changes once.

**Review by utkarsh0702 — CHANGES_REQUESTED** [review]
@aayushibansal2001  The notebook looks good. Please attach the model along with it in .pkl format.

**Comment by aayushibansal2001** [comment]
There was many merge conflicts in this pull request, so I am creating a new pull request #193.

**Pull request closed without merging**
